--
-- PostgreSQL database dump
--
-- Dumped from database version 13.1
-- Dumped by pg_dump version 13.1
SET statement_timeout = 0;

SET lock_timeout = 0;

SET idle_in_transaction_session_timeout = 0;

SET client_encoding = 'UTF8';

SET standard_conforming_strings = ON;

SELECT
  pg_catalog.set_config('search_path', '', FALSE);

SET check_function_bodies = FALSE;

SET xmloption = content;

SET client_min_messages = warning;

SET row_security = OFF;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: flyway_schema_history; Type: TABLE; Schema: public; Owner: -
--
CREATE TABLE public.flyway_schema_history (
  installed_rank integer NOT NULL,
  version character varying(50),
  description character varying(200) NOT NULL,
  type character varying(20) NOT NULL,
  script character varying(1000) NOT NULL,
  checksum integer,
  installed_by character varying(100) NOT NULL,
  installed_on timestamp without time zone DEFAULT now() NOT NULL,
  execution_time integer NOT NULL,
  success boolean NOT NULL
);

--
-- Name: smart_cities; Type: TABLE; Schema: public; Owner: -
--
CREATE TABLE public.smart_cities (
  id integer NOT NULL,
  data text
);

--
-- Name: smart_cities_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--
ALTER TABLE public.smart_cities
  ALTER COLUMN id
  ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME
    public.smart_cities_id_seq START WITH 1 INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1);

--
-- Name: flyway_schema_history flyway_schema_history_pk; Type: CONSTRAINT; Schema: public; Owner: -
--
ALTER TABLE ONLY public.flyway_schema_history
  ADD CONSTRAINT flyway_schema_history_pk PRIMARY KEY (installed_rank);

--
-- Name: smart_cities smart_cities_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--
ALTER TABLE ONLY public.smart_cities
  ADD CONSTRAINT smart_cities_pkey PRIMARY KEY (id);

--
-- Name: flyway_schema_history_s_idx; Type: INDEX; Schema: public; Owner: -
--
CREATE INDEX flyway_schema_history_s_idx ON public.flyway_schema_history USING
  btree (success);

--
-- PostgreSQL database dump complete
--
